# Generated by Django 5.2.3 on 2025-09-29 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lesson_generator", "0002_rename_created_at_lessonplan_created_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lessonplan",
            name="teacher_actions",
            field=models.TextField(blank=True),
        ),
    ]
