# Generated by Django 5.2.3 on 2025-09-30 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lesson_generator", "0003_lessonplan_teacher_actions"),
    ]

    operations = [
        migrations.AddField(
            model_name="lessonplan",
            name="student_requirements",
            field=models.TextField(blank=True),
        ),
    ]
